CategoriesAndSizes/urls.py
from django.urls import re_path, path
from . import views

# namespace
app_name = "CategoriesAndSizes"

urlpatterns = [
    path('', views.file_list, name='file_list'),
    path('categories/', views.listCategories),
    path('categories/add/', views.createCategory),
    path('categories/del/<id>', views.deleteCategory),
    path('categories/edit/<id>', views.editCategory),
    path('categories/update/', views.updateCategory),
    path('talles/<idCategory>', views.listSizes),
    path('talles/add/', views.createSize),
    path('talles/edit/<id>/<idCat>', views.editSize),
    path('talles/update/', views.updateSize),
    path('talles/del/<id>/<idCat>', views.deleteSize),
    re_path(r'^upload/$', views.model_form_upload, name='model_form_upload'),
    re_path(r'^delete/$', views.model_delete, name='model_delete'),
    re_path(r'^download/(?P<id>.*)/$', views.file_response_download, name='file_download'),
    path('pdf/', views.export_pdf_categories, name="export-pdf_categories"),
    path('export_pdf_sizes/<id>', views.export_pdf_sizes, name='export_pdf_sizes'),
]

accounts/urls.py
from django.urls import re_path, path
from . import views

# namespace
app_name = "accounts"

urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

taho/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

import CategoriesAndSizes.views

urlpatterns = [
    path("", CategoriesAndSizes.views.home, name="home"),
    path("files/", include('CategoriesAndSizes.urls')),
    path("accounts/", include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CategoriesAndSizes/models.py
from django.db import models
import os
import uuid

class SizeCategory(models.Model):
    id = models.AutoField(primary_key=True)
    description = models.CharField(max_length=60)

    def __str__(self):
        return self.description

class Size(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=30)
    categories = models.ManyToManyField(SizeCategory)
    
    def __str__(self):
        return self.name


def user_directory_path(instance, filename):
    ext = filename.split('.')[-1]
    filename = '{}.{}'.format(uuid.uuid4().hex[:10], ext)
    return os.path.join("files", filename)

class File(models.Model):
    id = models.AutoField(primary_key=True)
    file = models.FileField(upload_to=user_directory_path, null=True)
    original_name = models.CharField(max_length=150, verbose_name='Nombre original', blank=True)

CategoriesAndSizes/forms.py
from django import forms
from .models import File

# Model form
class FileUploadModelForm(forms.ModelForm):
    class Meta:
        model = File
        fields = ('file','original_name')

        widgets = {
            'file': forms.ClearableFileInput(attrs={'class': 'form-control'}),
            'original_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Este campo se rellena solo'}),
        }

    def clean_file(self):
        file = self.cleaned_data['file']
        ext = file.name.split('.')[-1].lower()
        if ext not in ["csv"]:
            raise forms.ValidationError("Solo aceptamos archivos .csv")
        return file
    
    def clean_original_name(self):
        file = self.cleaned_data.get('file')
        if file != None:
            return file.name

CategoriesAndSizes/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.template.loader import render_to_string
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.http import FileResponse, Http404
from weasyprint import HTML
import os
from .forms import FileUploadModelForm
from .models import SizeCategory, Size, File
from .procesar_csv import procesarCSV

def home(request):
    return render(request, "home.html")

@login_required(login_url="/accounts/login/")
def listCategories(request):
    allCategories = SizeCategory.objects.all()
    return render(request, 'crudCategories.html', {'categories': allCategories})

@login_required(login_url="/accounts/login/")
def listSizes(request, idCategory):
    categoria = SizeCategory.objects.get(id=idCategory)
    sizes = SizeCategory.objects.get(id=idCategory).size_set.all()
    return render(request, 'crudTalles.html', {'category': categoria, 'sizes': sizes})

@login_required(login_url="/accounts/login/")
def createCategory(request):
    nombre = request.POST['txtDescription']
    categoria = SizeCategory.objects.create(description=nombre)
    return redirect('/files/categories/')

@login_required(login_url="/accounts/login/")
def createSize(request):
    idCategoria = request.POST['txtIdCat']
    nombre = request.POST['txtNombreSize']
    categoria = SizeCategory.objects.get(id=idCategoria)
    size = Size(name=nombre)
    size.save()
    size.categories.add(categoria)
    return redirect('/files/talles/' + idCategoria)

@login_required(login_url="/accounts/login/")
def editCategory(request, id):
    categoria = SizeCategory.objects.get(id=id)
    return render(request, "editCategory.html", {"category": categoria})

@login_required(login_url="/accounts/login/")
def editSize(request, id, idCat):
    talle = Size.objects.get(id=id)
    return render(request, "editSize.html", {"size": talle, "category": idCat})

@login_required(login_url="/accounts/login/")
def deleteCategory(request, id):
    categoria = SizeCategory.objects.get(id=id)
    categoria.delete()
    return redirect('/files/categories/')

@login_required(login_url="/accounts/login/")
def deleteSize(request, id, idCat):
    size = Size.objects.get(id=id)
    size.delete()
    return redirect('/files/talles/' + idCat)

@login_required(login_url="/accounts/login/")
def updateCategory(request):
    id = request.POST['txtId']
    nombre = request.POST['txtDescription']
    categoria = SizeCategory.objects.get(id=id)
    categoria.description = nombre
    categoria.save()
    return redirect('/files/categories/')

@login_required(login_url="/accounts/login/")
def updateSize(request):
    id = request.POST['txtId']
    nombre = request.POST['txtNombre']
    idCategoria = request.POST['txtCategoria']
    talle = Size.objects.get(id=id)
    talle.name = nombre
    talle.save()
    return redirect('/files/talles/' + idCategoria)

@login_required(login_url="/accounts/login/")
def file_list(request):
    files = File.objects.all().order_by("-id")
    deletedFiles = False
    for f in files:
        if not f.file.storage.exists(f.file.name):
            f.delete()
            deletedFiles = True
    if deletedFiles:
        files = File.objects.all().order_by("-id")
    return render(request, 'file_list.html', {'files': files})

@login_required(login_url="/accounts/login/")
def model_form_upload(request):
    if request.method == "POST":
        form = FileUploadModelForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect("/files/")
    else:
        form = FileUploadModelForm()
    return render(request, 'upload_form.html', {'form': form, 'heading': 'Subir csv para agregarle los Sizes'})

@login_required(login_url="/accounts/login/")
def file_response_download(request, id):
    file = File.objects.get(pk=id)
    file_path = file.file.url[1:]
    media_root = getattr(settings, 'MEDIA_ROOT', None)
    ext = os.path.basename(file_path).split('.')[-1].lower()
    if ext in ['csv']:
        todoOK = procesarCSV(os.path.join(media_root, 'files', os.path.basename(file.file.url)))
        if todoOK[0] == 'OK':
            response = FileResponse(open(file_path, 'rb'))
            response['content_type'] = "application/octet-stream"
            response['Content-Disposition'] = 'attachment; filename=' + os.path.basename(file_path)
            return response
        else:
            return render(request, 'errors_list.html', {'errors': todoOK})
    else:
        raise Http404

@login_required(login_url="/accounts/login/")
def model_delete(request):
    media_root = getattr(settings, 'MEDIA_ROOT', None)
    records = File.objects.all()
    for f in records:
        fileName = os.path.join(media_root, 'files', os.path.basename(f.file.url))
        if os.path.isfile(fileName):
            os.remove(fileName)
    records.delete()
    return render(request, 'file_list.html', {'files': records})

@login_required(login_url="/accounts/login/")
def export_pdf_categories(request):
    categories = SizeCategory.objects.all()
    context = {}
    for c in categories:
        context[c.id] = c.description
    html = render_to_string("report-pdf.html", {'context': context})
    response = HttpResponse(content_type="application/pdf")
    response["Content-Disposition"] = "inline; report.pdf"
    HTML(string=html).write_pdf(response)
    return response

@login_required(login_url="/accounts/login/")
def export_pdf_sizes(request, id):
    categoria = SizeCategory.objects.get(id=id)
    sizes = SizeCategory.objects.get(id=id).size_set.all()
    talles = {}
    for size in sizes:
        talles[size.id] = size.name
    html = render_to_string("report-talles.html", {'categoria': categoria.description, 'sizes': talles})
    response = HttpResponse(content_type="application/pdf")
    response["Content-Disposition"] = "inline; report.pdf"
    HTML(string=html).write_pdf(response)
    return response

CategoriesAndSizes/templates/base.html
<!DOCTYPE html>
<html>
<head>
  {% load static %}
<title>{% block title %} {% endblock %}</title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" 
  rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" 
  crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
  <nav class="navbar navbar-expand-md navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Home</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-md-0">
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/accounts/signup/">Registrar Usuario</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/files/categories/">Categorías y Talles</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/files/">Procesar archivos</a>
        </li>
        {% endif %}
      </ul>
      {% if user.is_authenticated %}
      <form class="d-flex" action="{% url 'accounts:logout'%}" method="post">
         {% csrf_token %}
        <button class="btn btn-outline-success" type="submit">Logout</button>
      </form>
      {% else %}
        <a class="nav-link active btn btn-outline-success" aria-current="page" href="/accounts/login/">Login</a>
      {% endif %}
    </div>
  </div>
</nav>

{% block content %}{% endblock %}

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" 
integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" 
crossorigin="anonymous"></script>
</body>
</html>

CategoriesAndSizes/templates/basepdf.html
<!doctype html>
<html lang="es">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Reporte PDF</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <style>
        @page {
            size: "A4";
            margin: 1.0cm 1.5cm 3.5cm 1.5cm;
        }

        body {
            width: 100% !important;
            height: 100%;
            background: #fff;
            color: black;
            font-size: 100%;
            font-family: 'Roboto', sans-serif;
            line-height: 1.65;
            -webkit-font-smoothing: antialiased;
            -webkit-text-size-adjust: none;
        }
    </style>
</head>

<body>
    <main class="container">
        {% block content %}
        {% endblock %}
    </main>
</body>

</html>

CategoriesAndSizes/templates/crudCategories.html
{% extends "base.html" %}
{% block title %}Categorías{% endblock %}
{% block content %}
<div class="container py-4">
    <div class="row">
        <div class="col-sm-12 col-md-6 col-lg-4 col-xl-4">
            <h2>Categorías de talles</h2>
            <div class="card">
                <div class="card-body">
                    <form action="add/" method="POST">{% csrf_token %}
                        <div class="mb-3">
                            <label for="txtDescription" class="form-label">Nombre de la categoría</label>
                            <input type="text" id="txtDescription" name="txtDescription" class="form-control"
                                maxlength="50" required>
                        </div>
                        <div class="d-grid">
                            <button type="submit" class="btn btn-primary">Guardar Categoría</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-sm-12 col-md-6 col-lg-8 col-xl-8">
            <div class="table-responsive py-2">
                <h1>Listado de Categorías de Talles</h1>
                <a href="../pdf/" class="btn btn-info">Generar PDF</a>
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>id</th>
                            <th>Nombre</th>
                            <th>Opciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for c in categories %}
                        <tr>
                            <td>{{forloop.counter}}</td>
                            <td>{{c.id}}</td>
                            <td>{{c.description}}</td>
                            <td>
                                <a href="edit/{{c.id}}" class="btn btn-info">Editar</a>
                                <a href="del/{{c.id}}" class="btn btn-danger btnEliminar">Eliminar</a>
                                <a href="../talles/{{c.id}}" class="btn btn-info">Ver Talles</a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}

CategoriesAndSizes/templates/crudTalles.html
{% extends "base.html" %}
{% block title %}Talles{% endblock %}
{% block content %}
<div class="container py-4">
    <div class="row">
        <div class="col-sm-12 col-md-6 col-lg-4 col-xl-4">
            <h2>Categoría: <em>{{category.description}}</em></h2>
            <div class="card">
                <div class="card-body">
                    <form action="add/" method="POST">{% csrf_token %}
                        <div class="mb-3">
                            <label for="txtIdCat" class="form-label">Id de la categoría</label>
                            <input type="text" id="txtIdCat" name="txtIdCat" class="form-control" 
                            value="{{category.id}}"  readonly>
                        </div>
                        <div class="mb-3">
                            <label for="txtDescCat" class="form-label">Nombre de la categoría</label>
                            <input type="text" id="txtDescCat" name="txtDescCat" class="form-control" 
                            value="{{category.description}}" readonly>
                        </div>
                        <div class="mb-3">
                            <label for="txtNombreSize" class="form-label">Nombre del talle</label>
                            <input type="text" id="txtNombreSize" name="txtNombreSize" class="form-control" 
                            maxlength="50"  required>
                        </div>
                        <div class="d-grid">
                            <button type="submit" class="btn btn-primary">Guardar Size</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-sm-12 col-md-6 col-lg-8 col-xl-8">
            <div class="table-responsive py-2">
                <h1>Listado de Talles</h1>
                <a href="../export_pdf_sizes/{{category.id}}" class="btn btn-info">Generar PDF</a>
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>id</th>
                            <th>Nombre</th>
                            <th>Opciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for talle in sizes %}
                        <tr>
                            <td>{{forloop.counter}}</td>
                            <td>{{talle.id}}</td>
                            <td>{{talle.name}}</td>
                            <td>
                                <a href="edit/{{talle.id}}/{{category.id}}" class="btn btn-info">Editar</a>
                                <a href="del/{{talle.id}}/{{category.id}}" class="btn btn-danger btnEliminar">Eliminar</a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}

CategoriesAndSizes/templates/editCategory.html
{% extends "base.html" %}
{% block title %}Categorías{% endblock %}
{% block content %}
<div class="container py-4">
    <div class="row">
        <h2>Editar la Categoría</h2>
        <div class="card">
            <div class="card-body">
                <form action="../update/" method="POST">{% csrf_token %}
                    <div class="mb-3">
                        <label for="txtId" class="form-label">Identificador interno</label>
                        <input type="text" id="txtId" name="txtId" value="{{category.id}}" class="form-control" readonly required>
                    </div>
                    <div class="mb-3">
                        <label for="txtDescription" class="form-label">Nombre de la categoría</label>
                        <input type="text" id="txtDescription" name="txtDescription" value="{{category.description}}" class="form-control"
                            maxlength="50" required>
                    </div>
                    <div class="d-grid">
                        <button type="submit" class="btn btn-primary">Guardar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

CategoriesAndSizes/templates/editSize.html
{% extends "base.html" %}
{% block title %}Talles{% endblock %}
{% block content %}
<div class="container py-4">
    <div class="row">
        <h2>Editar el nombre del Talle</h2>
        <div class="card">
            <div class="card-body">
                <form action="/files/talles/update/" method="POST">{% csrf_token %}
                    <div class="mb-3">
                        <label for="txtCategoria" class="form-label">Número de Categoría</label>
                        <input type="text" id="txtCategoria" name="txtCategoria" value="{{category}}" class="form-control" readonly>
                    </div>
                    <div class="mb-3">
                        <label for="txtId" class="form-label">Identificador interno</label>
                        <input type="text" id="txtId" name="txtId" value="{{size.id}}" class="form-control" readonly
                            required>
                    </div>
                    <div class="mb-3">
                        <label for="txtNombre" class="form-label">Nombre del Talle</label>
                        <input type="text" id="txtNombre" name="txtNombre" value="{{size.name}}"
                            class="form-control" maxlength="50" required>
                    </div>
                    <div class="d-grid">
                        <button type="submit" class="btn btn-primary">Guardar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

CategoriesAndSizes/templates/errors_list.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="container py-4">
    <h3>Errores encontrados al procesar el archivo</h3>
    <p> <a href="/files/">Lista de archivos subidos</a></p>
    {% if errors %}
    <table class="table table-striped">
        <tbody>
            <tr>
                <td>Error</td>
            </tr>
            {% for e in errors %}
            <tr>
                <td>{{e}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
    <p>No se encontraron errores. Haz click <a href="{% url 'file_upload:model_form_upload' %}">aquí</a>
        para subir archivos.</p>
    {% endif %}
</div>
{% endblock %}

CategoriesAndSizes/templates/file_list.html
{% extends "base.html" %}
{% block title %}Lista de archivos{% endblock %}
{% block content %}

<div class="container py-4">
    <h3>Lista de archivos</h3>
    <p> <a href="/files/upload/">Subir archivo</a> |
        <a href="/files/delete/">Borrar los archivos</a>
    </p>
    {% if files %}
    <table class="table table-striped">
        <tbody>
            <tr>
                <td>Nombre</td>
                <td>Nombre original</td>
                <td>Tamaño</td>
            </tr>
            {% for file in files %}
            <tr>
                <td><a href="/files/download/{{ file.id }}">{{ file.file.url }}</a></td>
                <td>{{file.original_name}}</td>
                <td>{{ file.file.size | filesizeformat }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
    <p>No hay archivos todavía. Haz click <a href="{% url 'CategoriesAndSizes:model_form_upload' %}">aquí</a>
        para subir archivos.</p>
    {% endif %}
</div>
{% endblock %}

CategoriesAndSizes/templates/home.html
{% extends "base.html" %}
{% block title %}Convertir csv{% endblock %}
{% block content %}

<div class="container-fluid text-center home mb-5">
  <div class="container p-5">
    <h1>Aplicación para generar archivos csv con todos los Sizes por Categoría</h1>
    <p>La idea es subir al sitio los archivos csv de ofertas pre-book con Size-category pero sin valor en Size y poder
      bajar el archivo procesado con todos los Sizes para cada categoría, para luego poder importar correctamente la oferta.
    </p>
  </div>
</div>
<div class="container">
  <div class="alert alert-info text-center">
    Esta aplicación web mantendrá los archivos subidos tan solo por unos minutos.
  </div>
</div>
{% endblock %}

CategoriesAndSizes/templates/report-pdf.html
{% extends "basepdf.html" %}
{% block content %}
<h1 class="text-center">Categorías de Talles</h1>
<br>
<h4 class="text-center">Es necesario que estas categorías coincidan con las ingresadas en Salesforce</h4>
<table>
    <tr>
        <th>Nombre de la Categoría</th>
    </tr>
    {% for key, value in context.items %}
    <tr>
        <td>{{ value }}</td>
    </tr>
    {% endfor %}

</table>
{% endblock %}

CategoriesAndSizes/templates/report-talles.html
{% extends "basepdf.html" %}
{% block content %}
<h1 class="text-center">Sizes para la Categoría: {{ categoria }}</h1>
<br>
<h4 class="text-center">Es necesario que estos Sizes coincidan con los ingresados en Salesforce</h4>
<table>
    <tr>
        <th>Nombre del Size</th>
    </tr>
    {% for key, value in sizes.items %}
    <tr>
        <td>{{ value }}</td>
    </tr>
    {% endfor %}

</table>
{% endblock %}

CategoriesAndSizes/templates/upload_form.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="container py-4">
    {% if heading %}
    <h3>{{ heading }}</h3>
    {% endif %}
    <p> <a href="/files/">Lista de archivos subidos</a></p>

    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-info form-control " type="submit" value="submit">Subir archivo</button>
    </form>
</div>

{% endblock %}